name: env_asv_public_aarch64
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - pandas
  - scipy
  - scikit-learn
  - librosa
  - pysoundfile
  - tqdm
  - sentencepiece
  - pyyaml
  - setuptools
  - pip:
      - attrs
      - cloudpickle
      - ml-dtypes
      - psutil
      - tornado
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - torch-npu==2.1.0.post8
      - speechbrain==0.5.16
      - hyperpyyaml
      - nnAudio==0.3.3
      - ptflops==0.7.3
